url: https://board.sample.es
port: 6969
log_level: debug
jwt_secret: un-secreto-muy-secreto
jwt_expires_in: 60m
jwt_maxage: 60
board_name: DockerBoard
users:
  - name: user1
    password: password1
    active: true
  - name: user2
    password: password2
    active: false
  - name: user3
    password: password3
    active: true
categories:
  - name: Category1
    description: Category1 description
    icon: fa-solid fa-music
  - name: Category2
    description: Category2 description
    icon: user
